const Map<String, String> countriesISO = {
  "Afghanistan": "af",
  "Albanie": "al",
  "Algérie": "dz",
  "Andorre": "ad",
  "Angola": "ao",
  "Antigua-et-Barbuda": "ag",
  "Argentine": "ar",
  "Arménie": "am",
  "Australie": "au",
  "Autriche": "at",
  "Azerbaïdjan": "az",
  "Bahamas": "bs",
  "Bahreïn": "bh",
  "Bangladesh": "bd",
  "Barbade": "bb",
  "Biélorussie": "by",
  "Belgique": "be",
  "Belize": "bz",
  "Bénin": "bj",
  "Bhoutan": "bt",
  "Bolivie": "bo",
  "Bosnie-Herzégovine": "ba",
  "Botswana": "bw",
  "Brésil": "br",
  "Brunei": "bn",
  "Bulgarie": "bg",
  "Burkina Faso": "bf",
  "Burundi": "bi",
  "Cabo Verde": "cv",
  "Côte d'Ivoire": "ci",
  "Cambodge": "kh",
  "Cameroun": "cm",
  "Canada": "ca",
  "République centrafricaine": "cf",
  "Tchad": "td",
  "Chili": "cl",
  "Chine": "cn",
  "Colombie": "co",
  "Comores": "km",
  "Congo": "cg",
  "République démocratique du Congo": "cd",
  "RD Congo": "cd",
  "Costa Rica": "cr",
  "Croatie": "hr",
  "Cuba": "cu",
  "Chypre": "cy",
  "République tchèque": "cz",
  "Danemark": "dk",
  "Djibouti": "dj",
  "Dominique": "dm",
  "République dominicaine": "do",
  "Équateur": "ec",
  "Égypte": "eg",
  "El Salvador": "sv",
  "Guinée équatoriale": "gq",
  "Érythrée": "er",
  "Estonie": "ee",
  "Eswatini": "sz",
  "Éthiopie": "et",
  "Fidji": "fj",
  "Finlande": "fi",
  "France": "fr",
  "Gabon": "ga",
  "Gambie": "gm",
  "Géorgie": "ge",
  "Allemagne": "de",
  "Ghana": "gh",
  "Grèce": "gr",
  "Grenade": "gd",
  "Guatemala": "gt",
  "Guinée": "gn",
  "Guinée-Bissau": "gw",
  "Guyana": "gy",
  "Haïti": "ht",
  "Honduras": "hn",
  "Hongrie": "hu",
  "Islande": "is",
  "Inde": "in",
  "Indonésie": "id",
  "Iran": "ir",
  "Irak": "iq",
  "Irlande": "ie",
  "Israël": "il",
  "Italie": "it",
  "Jamaïque": "jm",
  "Japon": "jp",
  "Jordanie": "jo",
  "Kazakhstan": "kz",
  "Kenya": "ke",
  "Kiribati": "ki",
  "Koweït": "kw",
  "Kirghizistan": "kg",
  "Laos": "la",
  "Lettonie": "lv",
  "Liban": "lb",
  "Lesotho": "ls",
  "Libéria": "lr",
  "Libye": "ly",
  "Liechtenstein": "li",
  "Lituanie": "lt",
  "Luxembourg": "lu",
  "Madagascar": "mg",
  "Malawi": "mw",
  "Malaisie": "my",
  "Maldives": "mv",
  "Mali": "ml",
  "Malte": "mt",
  "Îles Marshall": "mh",
  "Mauritanie": "mr",
  "Maurice": "mu",
  "Mexique": "mx",
  "Micronésie": "fm",
  "Moldavie": "md",
  "Monaco": "mc",
  "Mongolie": "mn",
  "Monténégro": "me",
  "Maroc": "ma",
  "Mozambique": "mz",
  "Myanmar": "mm",
  "Namibie": "na",
  "Nauru": "nr",
  "Népal": "np",
  "Pays-Bas": "nl",
  "Nouvelle-Zélande": "nz",
  "Nicaragua": "ni",
  "Niger": "ne",
  "Nigéria": "ng",
  "Corée du Nord": "kp",
  "Macédoine du Nord": "mk",
  "Norvège": "no",
  "Oman": "om",
  "Pakistan": "pk",
  "Palaos": "pw",
  "Palestine": "ps",
  "Panama": "pa",
  "Papouasie-Nouvelle-Guinée": "pg",
  "Paraguay": "py",
  "Pérou": "pe",
  "Philippines": "ph",
  "Pologne": "pl",
  "Portugal": "pt",
  "Qatar": "qa",
  "Roumanie": "ro",
  "Russie": "ru",
  "Rwanda": "rw",
  "Saint-Kitts-et-Nevis": "kn",
  "Sainte-Lucie": "lc",
  "Saint-Vincent-et-les-Grenadines": "vc",
  "Samoa": "ws",
  "Saint-Marin": "sm",
  "Sao Tomé-et-Principe": "st",
  "Arabie saoudite": "sa",
  "Sénégal": "sn",
  "Serbie": "rs",
  "Seychelles": "sc",
  "Sierra Leone": "sl",
  "Singapour": "sg",
  "Slovaquie": "sk",
  "Slovénie": "si",
  "Îles Salomon": "sb",
  "Somalie": "so",
  "Afrique du Sud": "za",
  "Corée du Sud": "kr",
  "Soudan du Sud": "ss",
  "Espagne": "es",
  "Sri Lanka": "lk",
  "Soudan": "sd",
  "Suriname": "sr",
  "Suède": "se",
  "Suisse": "ch",
  "Syrie": "sy",
  "Taïwan": "tw",
  "Tadjikistan": "tj",
  "Tanzanie": "tz",
  "Thaïlande": "th",
  "Timor oriental": "tl",
  "Togo": "tg",
  "Tonga": "to",
  "Trinité-et-Tobago": "tt",
  "Tunisie": "tn",
  "Turquie": "tr",
  "Turkménistan": "tm",
  "Tuvalu": "tv",
  "Ouganda": "ug",
  "Ukraine": "ua",
  "Émirats arabes unis": "ae",
  "Royaume-Uni": "gb",
  "États-Unis": "us",
  "Uruguay": "uy",
  "Ouzbékistan": "uz",
  "Vanuatu": "vu",
  "Cité du Vatican": "va",
  "Venezuela": "ve",
  "Viêt Nam": "vn",
  "Yémen": "ye",
  "Zambie": "zm",
  "Zimbabwe": "zw"
};
